export const CHANGE_POKE_NAME = "CHANGE_POKE_NAME";
export const NEXT_PAGE = "NEXT_PAGE";
export const PREVIOUS_PAGE = "PREVIOUS_PAGE";
export const SET_MAX_PAGE = "SET_MAX_PAGE";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const CHANGE_SURVEY_STATUS = "CHANGE_SURVEY_STATUS";